"use client";

import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
import AdvancedServiceCard, { ServiceItemData } from "./service-card";

// --- DATA PUSAT (TAMBAHKAN DATA BARU DI SINI) ---
const servicesData: ServiceItemData[] = [
  {
    id: "residential-solar",
    title: "Hulu Dan Hilir Minyak dan Gas Bumi",
    subtitle: "Energi Rumah Mandiri",
    thumbnail: "/hulu-hilir-migas.jpg", // Gambar Kartu Depan
    content: {
      overview: {
        label: "Overview",
        image: "/max.jpg", // Gambar Header Modal (Tab 1)
        text: "Solusi panel surya atap untuk hunian modern yang hemat energi dan ramah lingkungan.",
        points: [
          "Hemat tagihan listrik hingga 40%",
          "Desain estetis menyatu dengan atap",
          "Monitoring via Aplikasi Mobile"
        ]
      },
      details: {
        label: "Spesifikasi Teknis",
        image: "/max.jpg", // Gambar Header Modal (Tab 2)
        text: "Detail teknis sistem Residential Solar kami.",
        points: [
          "Kapasitas: 1kWp - 10kWp",
          "Panel Type: Monocrystalline Full Black",
          "Garansi: 25 Tahun Output Daya"
        ]
      }
    }
  },
  {
    id: "hydropower-system",
    title: "Energi Dan Mineral Lainnya",
    subtitle: "Pembangkit Listrik Tenaga Air",
    thumbnail: "/energy-dan-mineral.jpg",
    content: {
      overview: {
        label: "Overview",
        image: "/max.jpg",
        text: "Pemanfaatan aliran air sungai dan bendungan untuk pembangkit listrik skala mikro hingga menengah.",
        points: [
          "Energi bersih dan stabil 24 jam",
          "Cocok untuk daerah pedesaan/terpencil",
          "Low maintenance cost"
        ]
      },
      details: {
        label: "Teknologi Turbin",
        image: "/max.jpg",
        text: "Spesifikasi turbin air yang kami gunakan.",
        points: [
          "Jenis Turbin: Kaplan & Francis",
          "Efisiensi Hidrolik: > 90%",
          "Material: Stainless Steel Anti-Korosi"
        ]
      }
    }
  },
  {
    id: "Jasa-Penunjang",
    title: "Jasa Penunjang",
    subtitle: "Tenaga Angin Efisien",
    thumbnail: "/jasa-penunjang.png",
    content: {
      overview: {
        label: "Overview",
        image: "/max.jpg",
        text: "Turbin angin canggih yang dirancang untuk memaksimalkan konversi energi bahkan pada kecepatan angin rendah.",
        points: [
          "Start-up speed rendah (2 m/s)",
          "Suara operasi senyap",
          "Tahan cuaca ekstrem"
        ]
      },
      details: {
        label: "Spesifikasi Rotor",
        image: "/max.jpg",
        text: "Detail teknis baling-baling dan generator.",
        points: [
          "Diameter Rotor: 10m - 50m",
          "Generator: Permanent Magnet (PMG)",
          "Tower Height: 20m - 80m"
        ]
      }
    }
  },
];

export default function AdvancedServiceSection() {
  return (
    <section className="bg-[#f2fcfc] md:py-20" id="ruang-lingkup">
      <div className="mx-4 md:mx-12 lg:mx-22 my-12 py-12 bg-[#e8f9f9] rounded-2xl">

        {/* Header Section */}
        <div className="gap-8 mb-12 mx-4 md:mx-10 lg:mx-16">
          <span className="inline-block bg-secondary/10 text-secondary text-sm font-semibold px-4 py-1 rounded-full">
            RUANG LINGKUP
          </span>
          <h2 className="text-4xl font-bold text-gray-900 mt-4">
            Our Solar Solutions
          </h2>
        </div>

        {/* Cards Grid (Generated by Data Loop) */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12 mx-4 md:mx-10 lg:mx-16">
          {servicesData.map((service) => (
            <AdvancedServiceCard
              key={service.id}
              item={service} // Kirim seluruh object data ke kartu
            />
          ))}
        </div>

        {/* View All Button */}
        <div className="flex justify-center mt-8">
          <a href="ruang-lingkup">
            <Button
              size="lg"
              className="bg-secondary hover:bg-secondary text-white font-semibold rounded-full 
                         px-8 py-4 text-base h-auto
                         shadow-lg shadow-secondary/40 hover:shadow-xl hover:shadow-secondary/50 
                         transition-all duration-300 ease-in-out hover:scale-105"
            >
              <ArrowRight className="w-5 h-5 mr-2" strokeWidth={2.5} />
              View all services
            </Button>
          </a>
        </div>

      </div>
    </section>
  );
}